### ISSUE TITLE
field [date] null in push notifications

### ISSUE THREAD

**Issue by clistenes** [driftyco/ionic-platform-web-client#141]
Hello, I do not know if this is the right place to post this problem and if not, please guide me to post in place. I have problem in sending push notifications for some users registered in ionic.io. Returns code 200, but the [data] field has no value. This only occurs for some users (android and ios). The biggest problem is when sending to multiple push tokens in the same request, and just be one with this problem, the shipment is blocked for all involved and no tokens receives the notification. Below are two examples reported in the case of Android platform above and then one ionic forum link where another user has the same problem with iOS platform.

**User OK:**

```
[data] => Array
        (
            [0] => stdClass Object
                (
                    [notification] => 1d32bd0a-a6c7-4fec-8bf8-21e46c12e2f8
                    [token] => stdClass Object
                        (
                            [token] => eX-Ssn3W_as:APA91bH98DzzhgkETX2n9Xy9UD6xmHtEdW6baqUaJhuxyvVcfIJv94Q7JPx3v37kJYKAN5IhvT3XcLBtZwacAaz5VnK5F1tmDGkmSqRVdUifMwLBdzEFZAZuhH-LvwlDuWVL5iDzqnUD
                            [app_id] => 1a34463d
                            [valid] => 1
                            [created] => 2016-08-18T14:44:33.957271+00:00
                            [type] => android
                            [id] => 676efd6bb4fe52ebd799976182a7c09f
                            [invalidated] => 
                        )

                    [status] => sent
                    [uuid] => d426a6c5-5166-4541-b168-a7e24689872a
                    [created] => 2016-08-26T13:27:13.574735+00:00
                    [error] => 
                    [user_id] => 
                )

        )

    [meta] => stdClass Object
        (
            [status] => 200
            [version] => 2.0.0-beta.0
            [request_id] => d463a05a-b69d-46fd-9221-8f55c3873378
        )
```

**User with the problem:**

```
[data] => Array
        (
        )

    [meta] => stdClass Object
        (
            [status] => 200
            [request_id] => 79aa512d-550a-41c7-9f54-32a1527b61b4
            [version] => 2.0.0-beta.0
        )
```

Link: [https://forum.ionicframework.com/t/ionic-1-push-notification/61679](https://forum.ionicframework.com/t/ionic-1-push-notification/61679)

**Comment by ericb** [comment]
What is the notification id of one of the notifications that does not give you any data?

**Comment by clistenes** [comment]
@ericb, Following the result of the notification to the user with the problematic token, it helps?

```
[data] => stdClass Object
        (
            [app_id] => 1a34463d
            [status] => open
            [uuid] => be94ecd3-46cd-4eeb-8821-8afb58b986a0
            [state] => enqueued
            [created] => 2016-08-26T15:12:51.768903+00:00
            [config] => stdClass Object
                (
                    [notification] => stdClass Object
                        (
                            [android] => stdClass Object
                                (
                                    [priority] => high
                                )

                            [ios] => stdClass Object
                                (
                                    [priority] => 10
                                    [badge] => 1
                                    [payload] => stdClass Object
                                        (
                                            [value] => 
                                            [$state] => 
                                            [param] => 
                                        )

                                    [sound] => default
                                )

                            [message] => Push enviando em 26/08/2016 12:12:51
                            [title] => Mensagem da Top3
                        )

                    [profile] => top_3_production
                    [tokens] => Array
                        (
                            [0] => eiEvb6sYDus:APA91bG2-Ayh1MskXGrYG37WujzKO1BhlJ-nlqX7L-VFkf4ShCuOUfPmpMTj79WjYaIXRdSKvVNG2WlyJvscKehv-UVRNYeIIF3K7Zw2rZKWOm1_QZWRicDC1BLClhanbcl6_U_8jZ9E
                        )

                )

        )

    [meta] => stdClass Object
        (
            [status] => 201
            [version] => 2.0.0-beta.0
            [request_id] => d53209c6-11b2-42a4-b760-e026d526a434
        )
```

**Comment by ericb** [comment]
@clistenes That's because the token has been invalidated. We recently stopped attempting to send to tokens that have been marked as invalid. We are working on a way to give an actual error response for those conditions.

**Comment by clistenes** [comment]
@ericb It is to just ignore these invalid tokens and not send notifications to them? Why is the following, let's say I send to 10 tokens and one of them is invalid as you mentioned, the remaining 9 not receive notifications. I made several tests to write it for you, including this example I mentioned in this post. When sending to multiple users, send normally, but just this token to be among those who will be sent, no one receives notification. Could see that, please?

**Comment by clistenes** [comment]
@ericb another thing, and in the case of another user who had the same problem I (cited in https://forum.ionicframework.com/t/ionic-1-push-notification/61679), he reports that sometimes returns the field "date" null and sometimes not. Here in this case, how would the token disability it?

**Comment by Fuiste** [comment]
@clistenes in the case of a token becoming invalidated, only that token will fail to receive a notification, not the entire list of recipients.

On my testing apps, I"m unable to reproduce the behavior you're describing wherein a single invalid token will cause delivery failure for the entire notification, but I'd first make sure that you can send to individual tokens as a way to zero in on the potential issue.

When the `data` field is null in a notification message listing, that means that we were not able to find any valid targets for a notification (either no tokens were supplied with the given `user_ids` or all tokens given were marked invalid).

**Comment by clistenes** [comment]
@Fuiste I will ask pushs here for tests to three users (2 phones are with me and the third is the token with the problem in question), so I'll paste here the call return code. So you can check the logs ... a moment.

**Comment by clistenes** [comment]
In this case below, none of the 3 (1 iOS and 2 Androids) receives the notification:

```
[data] => stdClass Object
        (
            [status] => open
            [uuid] => e359c452-2d1e-41f1-8e97-7ed6f4872e93
            [app_id] => 1a34463d
            [created] => 2016-08-26T16:58:32.791300+00:00
            [config] => stdClass Object
                (
                    [profile] => top_3_production
                    [tokens] => Array
                        (
                            [0] => eiEvb6sYDus:APA91bG2-Ayh1MskXGrYG37WujzKO1BhlJ-nlqX7L-VFkf4ShCuOUfPmpMTj79WjYaIXRdSKvVNG2WlyJvscKehv-UVRNYeIIF3K7Zw2rZKWOm1_QZWRicDC1BLClhanbcl6_U_8jZ9E
                            [1] => eX-Ssn3W_as:APA91bH98DzzhgkETX2n9Xy9UD6xmHtEdW6baqUaJhuxyvVcfIJv94Q7JPx3v37kJYKAN5IhvT3XcLBtZwacAaz5VnK5F1tmDGkmSqRVdUifMwLBdzEFZAZuhH-LvwlDuWVL5iDzqnUD
                            [2] => 15d44fca97f61969302853ce4bb2e4b228cf470de9c3b548ac2924265d137bfa
                        )

                    [notification] => stdClass Object
                        (
                            [title] => Mensagem da Top3
                            [android] => stdClass Object
                                (
                                    [priority] => high
                                    [payload] => stdClass Object
                                        (
                                            [param] => 
                                            [$state] => app.vagas
                                            [value] => 
                                        )

                                )

                            [ios] => stdClass Object
                                (
                                    [sound] => default
                                    [priority] => 10
                                    [badge] => 1
                                    [payload] => stdClass Object
                                        (
                                            [param] => 
                                            [$state] => app.vagas
                                            [value] => 
                                        )

                                )

                            [message] => Existem novas vagas disponíveis para recrutamento.
                        )

                )

            [state] => enqueued
        )

    [meta] => stdClass Object
        (
            [status] => 201
            [request_id] => e3d76aa3-b8d3-4bae-a4b6-3a327fe4f5a2
            [version] => 2.0.0-beta.0
        )
```

**Comment by Fuiste** [comment]
@clistenes  Is the `data` field empty in this case when you check the status on the `/notifications/<notification_id>/messages` endpoint?

**Comment by clistenes** [comment]
And in this case, now only 2 valid, both receive notification:

```
[data] => stdClass Object
        (
            [app_id] => 1a34463d
            [status] => open
            [uuid] => d1c30063-cb54-4d1d-a24c-0507593515db
            [state] => enqueued
            [created] => 2016-08-26T17:01:01.957527+00:00
            [config] => stdClass Object
                (
                    [notification] => stdClass Object
                        (
                            [android] => stdClass Object
                                (
                                    [priority] => high
                                    [payload] => stdClass Object
                                        (
                                            [value] => 
                                            [$state] => app.vagas
                                            [param] => 
                                        )

                                )

                            [ios] => stdClass Object
                                (
                                    [priority] => 10
                                    [badge] => 1
                                    [payload] => stdClass Object
                                        (
                                            [value] => 
                                            [$state] => app.vagas
                                            [param] => 
                                        )

                                    [sound] => default
                                )

                            [message] => Existem novas vagas disponíveis para recrutamento.
                            [title] => Mensagem da Top3
                        )

                    [profile] => top_3_production
                    [tokens] => Array
                        (
                            [0] => eX-Ssn3W_as:APA91bH98DzzhgkETX2n9Xy9UD6xmHtEdW6baqUaJhuxyvVcfIJv94Q7JPx3v37kJYKAN5IhvT3XcLBtZwacAaz5VnK5F1tmDGkmSqRVdUifMwLBdzEFZAZuhH-LvwlDuWVL5iDzqnUD
                            [1] => 15d44fca97f61969302853ce4bb2e4b228cf470de9c3b548ac2924265d137bfa
                        )

                )

        )

    [meta] => stdClass Object
        (
            [status] => 201
            [version] => 2.0.0-beta.0
            [request_id] => 778be57e-0836-4109-8c80-a1c29bf52d11
        )

```

**Comment by clistenes** [comment]
@Fuiste the status is 200. We have another case like mine, see this link:

[https://forum.ionicframework.com/t/push-notifications-are-not-received-when-sent-to-many-users-at-once/61714/1](https://forum.ionicframework.com/t/push-notifications-are-not-received-when-sent-to-many-users-at-once/61714/1)

**Comment by Fuiste** [comment]
@clistenes I'm wondering about the content of the `data` field when you check the messages endpoint for the given notifications, rather than the stsus.

**Comment by clistenes** [comment]
@Fuiste I'm trying to get the information, more to the endpoint messages is returning now 404 ... as if fallen. Stay here and trying to return ...

**Comment by clistenes** [comment]
@Fuiste I got now ... Here in this case with 2 tokens valid and invalid in question:

```
[data] => Array
        (
        )

    [meta] => stdClass Object
        (
            [status] => 200
            [request_id] => 6fc6fc4b-224a-47e3-8408-bed46797c643
            [version] => 2.0.0-beta.0
        )
```

**Comment by clistenes** [comment]
@Fuiste was this status that you needed?

**Comment by Fuiste** [comment]
@clistenes yup, thanks!

We've looked over things on our end and it looks like there was an issue with the way we were processing invalid tokens.  We've since deployed an update to the push server to address this and things should be good to go now.

Let me know if the problem persists!

**Comment by clistenes** [comment]
I tested with 3 tokens mentioned and actually sent, ie the invalid token was ignored. I was also sent to all users and not sent, returning status below (endpoint messages):

```
[meta] => stdClass Object
        (
            [version] => 2.0.0-beta.0
            [request_id] => f5a90ea6-e2fd-4154-be7e-b608733369b9
            [status] => 200
        )

    [data] => Array
        (
        )
```

**Comment by Bausen** [comment]
@clistenes Thanks for linking me!
@Fuiste i have the same problem like clistenes and it doesn't work now.

**Comment by clistenes** [comment]
Hello @Fuiste, any news about notifications?

**Comment by ericb** [comment]
@clistenes We pushed a fix last week that should have addressed your issue, are you still running into problems?

**Comment by Bausen** [comment]
Yes, i am running into problems too.

**Comment by clistenes** [comment]
Exactly, @ericb, I'm still having problems (follow status of endpoint messages below). As I mentioned in the previous post, with only the three tokens we've been testing it worked, but when released to all the [data] field is null:

```
[meta] => stdClass Object
        (
            [status] => 200
            [version] => 2.0.0-beta.0
            [request_id] => 913892e3-f993-461a-b0dd-12ad7c5fe0d8
        )

    [data] => Array
        (
        )
```

**Comment by Fuiste** [comment]
@clistenes We're still looking into these issues and have identified a potential cause of the problems you're having.  

We're working on a fix ASAP, and will update here when we've released.

**Comment by clistenes** [comment]
Ok @Fuiste, thank you. Awaiting.

**Comment by ericb** [comment]
@clistenes Just as a side note, is there a reason you're sending all device tokens manually, instead of using our [`send_to_all` targeting option](http://docs.ionic.io/api/endpoints/push.html#targeting-options)?

**Comment by Fuiste** [comment]
@clistenes one more thing, we've just scaled up more resources for the push server.  Can you confirm whether the problem is still occurring?

**Comment by clistenes** [comment]
@ericb I'm not using this option ...

**Comment by clistenes** [comment]
@Fuiste remains the problem. I will include the option that @ericb mentioned and return already with the answer.

**Comment by clistenes** [comment]
@Fuiste e @ericb, with the option "send_to_all" I started receiving notifications. In the first attempt, it took a while and came several notifications, as if they were arrested and came all at once. Then I waited and again requested the sending and arrived only one, that is apparently now is OK. I will monitor over the coming days and return to you. Thank you.

**Comment by Bausen** [comment]
Hello.
Sorry but i can't use the option "send_to_all" because i sent only to groups of persons who are interested in a specific topic. i hope you will work on this bug one more time...Thanks!

**Comment by clistenes** [comment]
@Fuiste e @ericb, reading @Bausen post, will need to remove this option in the near future, you will continue to correct this error?

**Comment by Fuiste** [comment]
@Bausen and @clistenes yes, we're still working on a fix for this issue.

**Comment by clistenes** [comment]
Thanks for listening. I will leave with the option to fix.

**Comment by Fuiste** [comment]
@clistenes we just pushed another update to the server.  Is the issue still happening on your end?

**Comment by clistenes** [comment]
@Fuiste I removed the option and made new test, but does not send notifications.

**Comment by furqan-dev** [comment]
Hi, i am also facing a similar issue. Not able to receive  any notification on either ios or android. As a test, I am sending a notification on an ios device. I have ensured the device token has not been invalidated since i am able to receive the notification when i test with APN Tester. The Initial response gives me 201 but when i check the notification status on 'https://api.ionic.io/push/notifications/uuid/messages'  i get an empty 'data' field.

My certificates are correct as i have mentioned earlier that I am able to receive the notification when i send it through APN Tester on mac.

**Comment by ericb** [comment]
@furqan-dev What is the notification id. It may have been invalidated in our system if it was sent with the wrong profile.

**Comment by furqan-dev** [comment]
@ericb Thanks for hearing me out. 

Notification id: c54e3729-94aa-4997-bcff-a7066ce96dc4

Following was the response i got when i sent the request..

`[data] => stdClass Object
        (
            [status] => open
            [uuid] => c54e3729-94aa-4997-bcff-a7066ce96dc4
            [created] => 2016-08-30T09:27:44.448746+00:00
            [config] => stdClass Object
                (
                    [tokens] => Array
                        (
                            [0] => 3cc352ee1829a30bd4a9f56d2f6d2d9a1b8cb388052c61a5b3ba9dc8905995e5
                        )

                    [profile] => production
                    [notification] => stdClass Object
                        (
                            [ios] => stdClass Object
                                (
                                    [badge] => 1
                                    [content_available] => 1
                                    [payload] => stdClass Object
                                        (
                                            [id] => 1472549262
                                            [addr] => 0
                                            [type] => 0
                                            [mls] => 0
                                        )

                                )

                            [android] => stdClass Object
                                (
                                    [payload] => stdClass Object
                                        (
                                            [id] => 1472549262
                                            [addr] => 0
                                            [type] => 0
                                            [mls] => 0
                                        )

                                    [message] => Hello ios
                                )

                            [message] => Hello ios
                        )

                )

            [state] => enqueued
            [app_id] => f4492352
        )

    [meta] => stdClass Object
        (
            [status] => 201
            [version] => 2.0.0-beta.0
            [request_id] => cffe1261-041d-49b6-b5d9-ef19fafbff36
        )
`

This is the response when i checked the status of the notification

`{
  "meta": {
    "request_id": "180325ff-12be-4d53-a3b8-afc18a0a17b7",
    "version": "2.0.0-beta.0",
    "status": 200
  },
  "data": []
}`

**Comment by ericb** [comment]
@furqan-dev Yeah, the token has been marked invalid in our system. Either that is a development environment token, or the wrong certificate has been updated to your `production` profile.

**Comment by clistenes** [comment]
@ericb, is the problem we are dealing with now is not related to invalid iOS tokens. The example of invalid token we started treating this problem was Android and you published a correction and it really worked. When libero sending to all tokens of my base (Android / iOS) it does not occur (without the option "send_to_all").

**Comment by ericb** [comment]
@clistenes Unrelated issue as far as i know. I've got a fix that will be going out shortly which should actually fix up the issue you're having. (It's possible you're running into something else entirely, but i'm guessing you will be good to go shortly here)

**Comment by clistenes** [comment]
@ericb excellent. Waiting for testing.

**Comment by furqan-dev** [comment]
That'd be great. Waiting impatiently since my app is in production.

**Comment by furqan-dev** [comment]
@ericb The token is fine as i mentioned I am using APN Tester. The certificate is also fine.

**Comment by ericb** [comment]
@furqan-dev You are not experiencing the same issue. As i mentioned your token has been marked invalid in our system due to one of the reasons I listed. You can manually mark it as valid again using our [API](http://docs.ionic.io/api/endpoints/push.html#patch-tokens-token_id), but it will likely just be marked as invalid again for the same reason it was previously.

**Comment by furqan-dev** [comment]
@ericb The token is generated via a production app, I am in fact using the production certificate. I am able to get a notification using [APN Tester](https://itunes.apple.com/us/app/apn-tester-free/id626590577?mt=12) using the same device token and the same production certificate. And i am not also able to receive notifications on Android. it is the same scenario as @clistenes has mentioned earlier in his issue. i have been able to receive the notifications earlier with the same profile, certificate and tokens. The issue arose some time earlier on Friday.

**Comment by ericb** [comment]
@furqan-dev I can look into the Android tokens if you provide me with a notification that used those. As for the iOS token, you should re-validate the token and send to it again. If you then check the status of the message, it should give you an error reason for invalidating the token.

**Comment by furqan-dev** [comment]
@ericb Thanks, i will try and write back to you.

**Comment by ericb** [comment]
@clistenes @Bausen I have pushed the fix for the issue I believe you are experiencing. Please let us know if it still has not addressed your specific issue.

**Comment by clistenes** [comment]
@ericb I did several tests now and is actually sending without send_to_all option. I will be monitoring the shipment and if there is any abnormality return to warn you. Again, thank you.

**Comment by ericb** [comment]
@clistenes Glad to hear it! 👍 Thanks for working with us on this.

**Comment by Bausen** [comment]
@ericb it seems to work again! Thanks for your help!
