### ISSUE TITLE
Push notifications are not being sent and no error is returned

### ISSUE THREAD

**Issue by kuroisuna** [driftyco/ionic-platform-web-client#16]
Hi guys,

Two days ago push notifications were doing great, but as of yesterday they are not being sent and this is the output of the message status (Ignore iOS since I'm using only Android):

```
{"status":"Failed","errors":[],"android":{"success":false,"failure_reason":"","sent":0},"app_id":"MYAPPID","ios":{"success":false,"failure_reason":"Push Error Code 302: See http://docs.ionic.io/docs/push-error-codes for more info.","sent":0}}
```

I'm not getting any kind of clue.

Thanks in advance.

**Comment by ericb** [comment]
You're getting a 302, which means that the APNS environment (production vs dev) you're attempting to send to does not have a certificate in our system. You'll need to make sure you upload your certificates for both production and development environments.

http://docs.ionic.io/docs/push-ios-setup#section-step-4-hooking-up-ionic-io

**Comment by kuroisuna** [comment]
Sure, thanks a lot for answering.

But I'm only interested in Android devices, I don't have any plan on supporting iOS. It doesn't sent pushes to android devices

**Comment by ericb** [comment]
The tokens you passed are either for iOS or they ahve been registered incorrectly. Do you have a message id I can look into?

**Comment by kuroisuna** [comment]
Sure =D

I configured my GMS keys with:

```
ionic push --google-api-key <GOOGLE GMS KEY>
ionic config set gcm_key <PROJECT NUMBER>
```
![image](https://cloud.githubusercontent.com/assets/4406617/10611022/1856cbda-7714-11e5-929c-f6ec47732a5c.png)

This is a message response:
`{"errors":[],"result":"queued","message_id":"1d446186773a11e58e41fa0ca6249b7e"}`

**Comment by ericb** [comment]
Ah okay, I believe this is an issue on our end. I'll post an update soon.

**Comment by Fuiste** [comment]
@kuroisuna looks like the logic we were using to detect iOS vs. Android tokens was to blame here.  I've just pushed up a fix to our push server which should solve the issue.  Good catch, and let me know if you have any further troubles.

**Comment by kuroisuna** [comment]
Thanks alot guys, the notifications are being received great!!!

**Comment by vsrboth** [comment]
@Fuiste I am still having this kind of bug. Please kindly see the following:

```
ionic push --google-api-key <GOOGLE GSM KEY>
ionic config set gcm_key <PROJECT NUMBER>
```

This is how I get from checking message status:

```
{"status":"Queued","ios":{"sent":0,"success":false,"failure_reason":""},"app_id":"787eb344","errors":[],"android":{"sent":0,"success":false,"failure_reason":""}}
```

**Comment by pareshmutha** [comment]
Hi ,
when i am pusing the message i getting below message

{"errors":[],"app_id":"ede2746d","android":{"failure_reason":"","success":false,"sent":0},"ios":{"failure_reason":"","success":false,"sent":0},"status":"Queued"}

not able receive notification on Desktop.

i have also done
ionic push --google-api-key <GOOGLE GSM KEY>
ionic config set gcm_key <PROJECT NUMBER>


can any one help me .
Thanks in advance.

**Comment by lexyfeito** [comment]
@pareshmutha Hey have you solve this problem, i am getting something similar.

**Comment by vsrboth** [comment]
@pareshmutha  @lexyfeito as I am well-aware about this issue. Ionic push is still in beta version. the one you are using on their web platform is all fake data.

**Comment by arychand282** [comment]
i'm stuck on that too.
{"errors":[],"ios":{"success":false,"failure_reason":"","sent":0},"app_id":"e8ad0bed","status":"Queued","android":{"success":false,"failure_reason":"","sent":0}}

how can i to solve this?
