### ISSUE TITLE
push duplicates on android

### ISSUE THREAD

**Issue by djangojack** [driftyco/ionic-platform-web-client#18]
I am getting duplicate notifications on Android like before. Here is my workflow:

User 1 login -> gets push token A
User 1 logs out -> unregisters token A
Push to token A fails (CORRECT)

User 1 logs in -> gets push token B
Push to token A succeeds (ERROR)
Push to user_ids = 1 -> Device receives 2 pushes (ERROR)

**Comment by ericb** [comment]
Strange, as far as i know that shouldn't be happening. I'll see if I can replicate. What platform are you using?

**Comment by djangojack** [comment]
I am using all the new stuff:

Cordova CLI: 5.2.0
Gulp version:  CLI version 3.9.0
Gulp local:   Local version 3.9.0
Ionic Version: 1.1.0
Ionic CLI Version: 1.7.6
Ionic App Lib Version: 0.6.2
OS: Windows 8.1
Node Version: v0.12.2

& latest ionic-platform-web-client  / phonegap-plugin-push plugin

**Comment by ericb** [comment]
But are you using android or ios?

**Comment by djangojack** [comment]
android

**Comment by Fuiste** [comment]
Quick question @djangojack.  Are tokens A and B distinct, or are they two multiples of the same one?

**Comment by djangojack** [comment]
@fuiste they are distinct

**Comment by Fuiste** [comment]
Sure thing @djangojack, and just to confirm, what method are you using to send the notifications?

**Comment by djangojack** [comment]
I push to user_ids and get duplicates.

 just went through the process and called unregister and got this:
`Ionic Push: unregistered push token: APA91bF7MK75milJg4_DfYTAemIC1gGgAlCwOWWW2f49vwIpqvsb3bjf-YhGenGN9X5WB2X9vhjSN3ZaT97hH4qt1rD4vPRVRcTNp8XPE70gUVuAdmzQoBlA2DqjBvYGJXAHGrvDTbRK ionic.io.bundle.min.js:2
unregister success 
Object {response: XMLHttpRequest, payload: ""}`

The object includes this:
`unregister success 
Object {response: XMLHttpRequest, payload: ""}
payload: ""
response: XMLHttpRequest
_id: "4: POST https://apps.ionic.io/api/v1/app/952ae98e/push/invalidate-token"
body: ""
id: "4: POST https://apps.ionic.io/api/v1/app/952ae98e/push/invalidate-token"`
...
...
`status: 200
statusCode: 200`

I then try to send a push to this token or the user_id and nothing happens (good!).

And then I tried logging out and logging in again and I got a completely different token (makes sense, its android). I then tried pushing to the original token (APA91bF7MK75milJg4_DfYTAemIC1gGgAlCwOWWW2f49vwIpqvsb3bjf-YhGenGN9X5WB2X9vhjSN3ZaT97hH4qt1rD4vPRVRcTNp8XPE70gUVuAdmzQoBlA2DqjBvYGJXAHGrvDTbRK) using curl and it went through (bad). Pushes to the user_id send multiple tokens (consistent & bad).

Whenever I logout, the device gets 0 pushes. The worst yet is when I login as a different user, I now get pushes to multiple users on the same device, which is really, really bad.

**Comment by Fuiste** [comment]
Ok @djangojack, I just pushed a fix to our server to address the multiple notifications issue.  It looks like we weren't properly checking the validity of tokens when sending via `user_id`.  Good catch there, and let me know if you have further issues.

As to your issue with logging in as different users, this is likely a result of the way token validity is stored.  We mark individual _tokens_ as valid or invalid with the `unregister()` call, so when a new user logs in, that token will be marked as valid again, and all users which have that token stored will be able to receive notifications on that device.

**Comment by djangojack** [comment]
@fuiste thanks

**Comment by djangojack** [comment]
@fuiste I am still getting multiple notifications.
I deleted the user and started the process over again to make sure I incorporated your new changes.

**Comment by eweap** [comment]
@Fuiste I've got the same issue as @djangojack 

It seems that Ionic don't delete the unregistered token. We can see that issue when we login/logout then login/logout again, there is still tokens registered on the Ionic User dashboard.

The weird thing is, when unregister a token, the unregister request is send to the webhook, but the token is still in the Ionic User dashboard.

Any news on this issue from Ionic team ?

Thanks

**Comment by djangojack** [comment]
@eweap, you need to call user.removepushtoken(token). Don't forget to call user.save() to update the server.
http://docs.ionic.io/docs/push-usage#section-integrating-with-ionic-user

**Comment by eweap** [comment]
@djangojack Oh ok ! I've totally forgot about  `user.save()` after removing the token, my bad ! Thanks man

**Comment by ykarthikreddy18** [comment]
Might be a irrelevant question, "Is there any API to get the device tokens from the ionic dash board, rather than storing them in the database? "

**Comment by lucasarts321** [comment]
I am stuck with this same problem can u share your solution this is what i am trying : 

if (window.localStorage['user'] != $scope.data.username) {
                    var success = function(loadedUser) {
                      Ionic.User.current(loadedUser);
                    };

                    var failure = function(error) {
                      console.log('something went wrong');
                    };

                    Ionic.User.load(window.localStorage['guid']).then(success, failure);
                    var push = new Ionic.Push();
                    var userOld = Ionic.User.current();                 
                    userOld.removePushToken(window.localStorage['token']);
                    userOld.save();
                    }     

Its not working i keep receiving push notifications for every single user logs into the app; by the way this code is inside the log in to avoid that. What i am missing ?
